uyuni-project/inter-server-sync

- dumper/dataCrawler.go
- dumper/types.go
table key values to be processed on data dumper was being saved as strings, and for that a method which formats the data according to is type as being used, which surrounds strings with `'`.
This leads to an error of not finding the needed records when dumping data.
With this change, we save the field interface.
> save key as interface instead of string

- dumper/channelDataDumper.go
- dumper/dataWritter.go
- main.go
- schemareader/tableFilters.go
- schemareader/types.go
- utils/utils.go
This PR makes use of CTE and the existing UPSERT command in a way that it captures the difference when inserting/updating the tables and then deletes the orphaned records. This is only for these tables which qualify for clean. This is to make the mentioned tables always in sync with the master channels so no orphaned records are left behind.
The syntax structure of the query is as follows.
```sql
WITH 
new_records_{tableName} AS ( INSERT INTO tableName....ON CONFLICT(keys) RETURNING keys)
, existing_records_{tableName} AS (SELECT keys INNER JOINS (till we reach rhnchannel and then stops) ....WHERE rhnchannel.id = (SELECT id FROM rhnchannel WHERE label = `replace-me`)) 
DELETE FROM {tableName} WHERE (keys) IN ( SELECT * FROM existing_records_{channelName} EXCEPT ALL SELECT * FROM …
```
> Create statements in a way that it removes the orphan records when inserting new records

- dumper/dataCrawler.go
- dumper/dataWriter.go
- entityDumper/channelDataDumper.go
separate table clean to a pre-step. 
This was done because of large channels. If we use the "with " clause, we will be loading a lot of data to memory, forcing postgres to use a huge memory footprint.
> Clean tables refactoring

- dumper/dataWriter.go
- dumper/packageDumper/packageDumper.go
- entityDumper/channelDataDumper.go
Reduces the memory used during data writing, since instead of loading to memory all records of one table it loads it in chunks.
> batch load key from database to export

- cmd/root.go
- release/hub-iss-logrotate.conf
- release/hub-iss-syslogs.conf
Instead of writing to a file directly, this PR will redirect logs to Syslog, making it independent from our application code. This also goes along the same guidelines as recommended in [12factor](https://12factor.net/logs) application guidelines.
This PR also adds a logrotate config file to handle the rotation of file.
> Redirect logs to syslog so is independent from our application as recommended in 12factor application guidelines

- dumper/dataWriter.go
- schemareader/tableFilters.go
After some changes in the table rhnPackageCapability, the inter server sync code needed to be adapted to cope with them.
Changes in the table definition: https://github.com/uyuni-project/uyuni/pull/4073/files#diff-e490c86128112eb64ffbefce85d10f854a6cc2ea019a88072d226ccf85387482
Fixes: https://github.com/SUSE/spacewalk/issues/16597
With this solution, we cope we all server versions. 
Since we are doing "ignore" in the on conflict clause, we can just skip the insert in case the record already exists.
To be able to have this behavior, we can create a virtual index on the conflicting columns, and use the same colunms.
It will check if the version is null, and behave acording.
> correct on conflict clause for rhnPackageCapability

- entityDumper/channelDataDumper.go
Bug fix for: https://github.com/SUSE/spacewalk/issues/16709
The table `rhnpackagekey` was not being exported with software channels.
> export rhnpackagekey table on software channels

- cmd/export.go
- dumper/crawler_test.go
- dumper/dataCrawler.go
- dumper/dataWriter.go
- dumper/writer_test.go
- entityDumper/channelDataDumper.go
- entityDumper/types.go
- utils/utils.go
- utils/utils_test.go
Fixes: https://github.com/SUSE/spacewalk/issues/16768
This PR allows to partially export software channels base on a starting date.
It will reduce the amount of data to be synchronized. The first synchronization should be full, which will take the same time as before, however, updates should be faster.
> software channels partial export based on date

- schemareader/tableFilters.go
Postgres lower case all table and column names, so when we are trying to do lookup in go table we need to have everything lowercase.
> Fix rhnchecksum table lookup, go is case sensitive

- dumper/dataWriter.go
During data writing, we keep a cache to avoid calls to database to collect lookups for foreign keys.
With this change, we clean this cache after a channel is processed since we don't expect channels to share that much data.
Fix for: https://github.com/SUSE/spacewalk/issues/16963
> clean lookup cache after processing a channel

- README.md
- inter-server-sync.changes
- inter-server-sync.spec
We are moving the changes and spec file from OBS to git, and get it automatically downloaded from git.
OBS project: https://build.opensuse.org/package/show/systemsmanagement:Uyuni:Master/inter-server-sync
> add changes file and spec in preparation to change build process

- cmd/import.go
- entityDumper/configurationDumper.go
Follow-up PR for configuration channels export which correct the detection to call XML-RPC API and remove some tables from the export list
> follow-up correction for configuration channels

- cmd/export.go
- cmd/import.go
- dumper/crawler_test.go
- dumper/dataCrawler.go
- dumper/dataWriter.go
- dumper/dumpAllTableData.go
- dumper/osImageDumper/osImageDumper.go
- dumper/packageDumper/packageDumper.go
- dumper/pillarDumper/pillarDumper.go
- dumper/utils.go
- dumper/writer_test.go
- entityDumper/channelDataDumper.go
- entityDumper/dumper.go
- entityDumper/imageDataDumper.go
- entityDumper/types.go
- entityDumper/utils.go
- schemareader/reader.go
- schemareader/reader_test.go
- schemareader/tableFilters.go
- utils/utils.go
Implementation of: https://github.com/SUSE/spacewalk/issues/15046
This PR adds options to export and import OS images.
Export by default exports both channels and images (tables, pillars and images), but this PR also adds an option to export only images.
Export can also be limited by organization id.
Import autodetect what everything is present in export folder and selectively import channels or images or both.
> Implement os image export and import

- inter-server-sync.changes
- schemareader/tableFilters.go
Correct the sequence name for table rhnpackagekey
> Correct sequence in use for table rhnpackagekey(bsc#1197400)

- entityDumper/imageDataDumper.go
- schemareader/tableFilters.go
- export image stores individually rather then dumping all tables
- export only built images if build column is present (feature of 4.3)
- create images and pillar directories only if needed
- add correct docker store, profile and image export
- do not export huge build logs
- include image revision in virtual index
> Container image export fixes and other improvements

- entityDumper/dumper.go
- inter-server-sync.changes
Implementation of: https://github.com/SUSE/spacewalk/issues/17722
Parameter --channel-with-children was not used to verify if we should export channels. Now we check and export data with it.
> Parameter --channel-with-children didn't export data(bsc#1199089)

- cmd/import.go
- cmd/root.go
- dumper/dataCrawler.go
- dumper/dataWriter.go
- dumper/packageDumper/packageDumper.go
- dumper/types.go
- dumper/utils_test.go
- dumper/writer_test.go
- entityDumper/channelDataDumper.go
- inter-server-sync.changes
Followup of: https://github.com/SUSE/spacewalk/issues/16963
Implementation of: https://github.com/SUSE/spacewalk/issues/17193
Improve memory usage in datacrawler.
This can be done by reducing the type of structure used in [1] which is responsible for 80%+ of the memory usage.
- Channel label: sle-module-basesystem15-updates-x86_64-sled
- Time in DataCrawler: 
- Base case: ~10min(+-30sec), from 14:34:52 to 14:44:52
- Improved case: ~10min(+-30sec), from 14:54:44 to 15:04:44
- Peak memory usage:
- Base case ~1433mb
- Improved case ~543mb
Before:
After:
[1] https://github.com/uyuni-project/inter-server-sync/blob/main/dumper/types.go#L9-L13
> Improve memory usage on software channels export

- dumper/crawler_test.go
- dumper/dataCrawler.go
- dumper/dataWriter.go
- dumper/utils_test.go
- dumper/writer_test.go
- inter-server-sync.changes
- schemareader/tableFilters.go
- tests/utils.go
implementation of: https://github.com/SUSE/spacewalk/issues/18767
In the tables clean generate step the insert statement needs to check if the target link table references are already present.
We were doing if just for the Unique Main constraint and not checking other foreign keys. This was fine for all tables except the rhnerratafile table.
This table has a link to rhnchecksum with is not part of the main unique index.
With this change, we keep adding all the columns in the main Unique index. After this is enhanced by adding a check for all checks.
An alternative implementation would be to ignore the main unique index and just add all refereces.
> 1202785 -  rhnerratafile error insert

- cmd/import.go
- inter-server-sync.changes
When running import without log level debug the debug flag was not added to the rsync call and the go command fails.
fix: https://github.com/SUSE/spacewalk/issues/19333
> Correct error with import without debug flag which fails on rsync

- inter-server-sync.changes
- utils/utils.go
Version detection is not working correctly. It relies on having a space in the product name, and the split is not done correctly.
This commit aims to solve this by comparing the parameter key with the wanted property and not relying on existing space before the product name.
> Correctly detect product name and product version number

- entityDumper/channelDataDumper.go
- inter-server-sync.changes.rmateus.main
When importing channels individually if the channel have some child channels it will not update the relationship automatically, and only at second import it will get updated.
the alternative to work around it it to make sure we first import the parent channel and then we can import all the child channels.
> create channel parent/child relationship when importing parent

- dumper/dataWriter.go
- dumper/dataWriter_test.go
- inter-server-sync.changes.rjmestre.dumper_encode_bytea_fields
Aims to fix https://github.com/SUSE/spacewalk/issues/23726
We detected a case where binary data contained backslashes. We've been using pq.QuoteLiteral but in these cases we end up getting invalid insert statements.
Besides, it also had some line breaks and contained sensitive information.
My suggestion here is to encode this type of data to hexadecimal as it would address the problems with escaping characters, keeps the statements tighter and also does not directly exposes any sensitive information that may be copied around servers.
We apply the same escape method to varchar fields. However i wanted to exclude them, at least for now. Encoding and decoding means having an additional processing overhead and this hasn't been a problem so far.
> Encode bytea fields

- .github/workflows/github-actions-tests.yml
- .github/workflows/reuse.yml
One of the recommendations of the [Good security practices for using GitHub Actions features](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions?learn=getting_started).
For each action I went to the repository and used the last released version for the major version we were using, and specified the exact version with a comment.
Be aware some actions are deprecated and archived, and for others we are using old 2.x version while most recent are 4.x. Feel free to create a card to trck it.
> Pin all GitHub actions to a commit

- inter-server-sync.changes.mbussolotto.logdir
- inter-server-sync.spec
logs are contained in `/var/log/hub`, but we're not listing the folder in the spec file
Issue: https://github.com/SUSE/spacewalk/issues/27352
> Package /var/log/hub (bsc#1243724)

- cmd/export.go
- entityDumper/channelDataDumper.go
- entityDumper/types.go
- inter-server-sync.changes.oholecek.skip_changelogs
Changelogs takes a significant amount of space and also increases export and import time.
This commit adds --noChangelogs option to skip exporting changelog data for packages.
Issue: https://github.com/SUSE/spacewalk/issues/27604
> Allow export without changelogdata (bsc#1245307)
